### ISSUE TITLE
data structures decision

### ISSUE THREAD

**Issue by d11deboer** [kevinvu01/CS1D-Team-Spanky#20]
We need to figure out which three data structure to implement. We already have a queue to store the trip restaurants in order. I think maybe a good ole linked list w/ iterator for the general pool of restaurants to choose from, but we need one more. Maybe a stack to hold the restaurants the user selects for a trip?

**Comment by haitrangnguyen** [comment]
Decided on: Stack for cart totals, Queue for ordered trip, Linked List for pool of resaturants
